
-- Joins request logs and waf logs in a nested fashion.

SELECT
rl.request_id, rl.timestamp, rl.service_id, rl.fastly_info, rl.req_referer, rl.datacenter, rl.client_ip, rl.city, rl.country_code, rl.continent_code, rl.latitude, rl.longitude, rl.req_method, rl.req_uri, rl.req_host, rl.req_user_agent, rl.req_header_bytes, rl.req_body_bytes, rl.req_accept, rl.req_accept_language, rl.req_accept_encoding, rl.req_accept_charset, rl.req_connection, rl.req_forwarded, rl.req_via, rl.req_x_requested_with, rl.req_x_requested_for, rl.waf_logged, rl.waf_blocked, rl.waf_failures, rl.waf_executed, rl.waf_passed, rl.anomaly_score, rl.sql_injection_score, rl.rfi_score, rl.lfi_score, rl.rce_score, rl.php_injection_score, rl.session_fixation_score, rl.http_violation_score, rl.xss_score, rl.resp_status, rl.resp_bytes, rl.resp_header_bytes, rl.resp_body_bytes, rl.tls_client_cipher, rl.tls_client_ciphers_list, rl.tls_client_protocol, rl.tls_client_tlsexts_list, rl.geo_ip_organization,
ARRAY_AGG(STRUCT(wl.rule_id as rule_id, wl.waf_message, wl.logdata, wl.severity, wl.anomaly_score)) as rules
FROM `fastly-solutions-eng.waf_demo.request_logs` as rl
LEFT OUTER JOIN `fastly-solutions-eng.waf_demo.waf_logs` as wl ON rl.request_id = wl.request_id
GROUP BY rl.request_id,rl.timestamp, rl.service_id, rl.fastly_info, rl.req_referer, rl.datacenter, rl.client_ip, rl.city, rl.country_code, rl.continent_code, rl.latitude, rl.longitude, rl.req_method, rl.req_uri, rl.req_host, rl.req_user_agent, rl.req_header_bytes, rl.req_body_bytes, rl.req_accept, rl.req_accept_language, rl.req_accept_encoding, rl.req_accept_charset, rl.req_connection, rl.req_forwarded, rl.req_via, rl.req_x_requested_with, rl.req_x_requested_for, rl.waf_logged, rl.waf_blocked, rl.waf_failures, rl.waf_executed, rl.waf_passed, rl.anomaly_score, rl.sql_injection_score, rl.rfi_score, rl.lfi_score, rl.rce_score, rl.php_injection_score, rl.session_fixation_score, rl.http_violation_score, rl.xss_score, rl.resp_status, rl.resp_bytes, rl.resp_header_bytes, rl.resp_body_bytes, rl.tls_client_cipher, rl.tls_client_ciphers_list, rl.tls_client_protocol, rl.tls_client_tlsexts_list, rl.geo_ip_organization
